services:
  #server:
    #build:
      #context: .
      #target: final
    #ports:
      #- 5107:8080
    #depends_on:
      #schoolhub-dev-db:
        #condition: service_healthy
    #env_file:
      #- .env

  schoolhub-dev-db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
